# Chart.yaml 파일은 Helm 차트에 대한 메타데이터를 정의합니다.
# 이 파일은 차트의 이름, 버전, 설명, 키워드, 유지 관리자 정보 등을 포함합니다.

# API 버전은 Helm 차트의 구조 버전을 나타냅니다.
# v2는 Helm 3에서 도입되었으며, 더 많은 기능을 제공합니다.
apiVersion: v2

# 차트의 이름입니다. 이름은 소문자와 숫자만 사용해야 하며, 대시(-)로 단어를 구분할 수 있습니다.
name: go-api

# 이 차트의 버전입니다. SemVer 2 표준을 따릅니다. (https://semver.org/)
# 차트가 업데이트될 때마다 이 버전도 업데이트해야 합니다.
version: 1.0.0

# 애플리케이션의 버전입니다. 배포할 애플리케이션의 실제 버전과 일치해야 합니다.
# 차트 버전과는 별개로, 실제 애플리케이션 코드의 버전을 의미합니다.
appVersion: "1.2.0"

# 차트 유형은 애플리케이션 배포 방식을 설명합니다.
# - application: 실행 가능한 애플리케이션을 배포 (기본값)
# - library: 재사용 가능한 차트 함수와 정의를 제공 (직접 배포되지 않음)
type: application

# 차트에 대한 간략한 한 줄 설명입니다.
description: Go로 작성된 백엔드 API 서비스를 위한 Helm 차트로, 개발, 스테이징, 프로덕션 환경을 지원합니다.

# 차트 홈페이지의 URL입니다. 내부 위키, 깃랩/깃허브 저장소 등이 될 수 있습니다.
# 이 URL은 `helm search` 명령어 결과에 표시됩니다.
home: https://github.com/mycompany/go-backend-roadmap

# 이 차트와 관련된 키워드 목록입니다. 이를 통해 차트 저장소에서 검색이 용이해집니다.
keywords:
  - go
  - golang
  - api
  - backend
  - microservice
  - kubernetes
  - helm

# 차트 소스 코드의 URL입니다. 주로 깃랩/깃허브 저장소 URL을 지정합니다.
sources:
  - https://github.com/mycompany/go-backend-roadmap/tree/main/05-cloud-native/docker-kubernetes/helm

# 차트의 유지 관리자 정보입니다. 이메일 주소를 포함해야 합니다.
# 이 정보는 문제 발생 시 연락을 위해 사용됩니다.
maintainers:
  - name: DevOps Team
    email: devops@mycompany.com
    url: https://mycompany.com/devops

# 차트의 아이콘 URL입니다. 차트 저장소 UI에서 표시될 수 있습니다.
icon: https://go.dev/images/go-logo-blue.svg

# 이 차트가 의존하는 다른 차트들의 목록입니다.
# 예를 들어, 이 애플리케이션이 Redis나 PostgreSQL 데이터베이스를 사용한다면
# 여기에 해당 차트 의존성을 명시할 수 있습니다.
dependencies:
  # Redis 캐시 서버에 대한 의존성 예시
  - name: redis
    version: "17.x.x"  # 사용할 Redis 차트의 버전 범위
    repository: "https://charts.bitnami.com/bitnami"  # 차트가 위치한 저장소 URL
    condition: redis.enabled  # values.yaml에서 redis.enabled가 true일 때만 설치
    tags:
      - cache
      - nosql
    
  # PostgreSQL 데이터베이스에 대한 의존성 예시
  - name: postgresql
    version: "12.x.x"  # 사용할 PostgreSQL 차트의 버전 범위
    repository: "https://charts.bitnami.com/bitnami"  # 차트가 위치한 저장소 URL
    condition: postgresql.enabled  # values.yaml에서 postgresql.enabled가 true일 때만 설치
    tags:
      - database
      - sql

# 애플리케이션에 대한 자세한 설명입니다. 마크다운 형식을 지원합니다.
# 차트 저장소 UI나 `helm show` 명령어로 볼 때 표시됩니다.
annotations:
  # 애플리케이션과 차트의 라이선스 정보입니다.
  # Helm v3에서는 'license' 필드 대신 'annotations'에 라이선스 정보를 추가하거나
  # 차트 내에 LICENSE 파일을 포함하는 것이 권장됩니다.
  # 아래는 annotations를 통한 라이선스 정보 명시 방법입니다.
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - 최초 차트 릴리스
    - Kubernetes 1.19+ 및 Helm 3.0+ 지원
    - 프로메테우스 메트릭 및 ServiceMonitor 지원 추가
    - HPA(Horizontal Pod Autoscaler) 통합
  artifacthub.io/prerelease: "false"  # 프리릴리스 여부
  artifacthub.io/containsSecurityUpdates: "false"  # 보안 업데이트 포함 여부
  artifacthub.io/operator: "false"  # 오퍼레이터 차트 여부
  artifacthub.io/operatorCapabilities: "Basic Install"  # 오퍼레이터 기능 수준 (해당될 경우)